[package]
name = "tokyo-library"
version = "0.1.0"
edition = "2021"

[dependencies]
tokyo-shadow = { path = "../shadow" }
tokyo-proto = { path = "../proto", features = ["protoc"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.105"
sha256 = "1.4.0"
walkdir = "2.3.3"
image = "0.24.7"
rawloader = "0.37.1"
rawler = { git = "https://github.com/tokyoapp/dnglab", rev = "11450c60e34e1deb7fa371e0a0a0b4e6e131c53b" }
roxmltree = "0.18"
tokio = "1.32.0"
anyhow = "1.0.75"
sysinfo = { version = "0.29.10", features = ["serde"] }
futures = "0.3.29"
libsql = { git = "https://github.com/tursodatabase/libsql", rev = "513941b768124985c8ca6c95e9dd3aa50410dc33" }
url = "2.5.0"
axum = { version = "0.6.20", features = ["ws", "macros"] }
env_logger = "0.10.1"
log = "0.4.20"
hyper = "1.1.0"

[dependencies.uuid]
version = "1.4.1"
features = ["v4"]
