[package]
name = "ccapi"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.10.1"
log = "0.4.20"
anyhow = "1.0.75"
futures = "0.3"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.12.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
